using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitle("FluentDynamoDb")]
[assembly: AssemblyDescription("Fluent, POCO friendly, convention-based mappings for DynamoDb. Get your fluent on :-)")]
[assembly: AssemblyVersionAttribute("2.1.0.999")]
[assembly: AssemblyFileVersionAttribute("2.1.0.999")]
[assembly: AssemblyCopyrightAttribute("Copyright 2013-2015")]
[assembly: AssemblyProductAttribute("FluentDynamoDB")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2.1.0.999")]
[assembly: InternalsVisibleTo("FluentDynamoDb.Tests")]
